CREATE TABLE IF NOT EXISTS senders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS campaigns (
  id INT AUTO_INCREMENT PRIMARY KEY,
  subject VARCHAR(500) NOT NULL,
  body TEXT NOT NULL,
  sender_id INT,
  delay_seconds INT NOT NULL DEFAULT 2,
  hourly_limit INT NOT NULL DEFAULT 100,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (sender_id) REFERENCES senders(id)
);

CREATE TABLE IF NOT EXISTS emails (
  id INT AUTO_INCREMENT PRIMARY KEY,
  campaign_id INT NOT NULL,
  recipient VARCHAR(255) NOT NULL,
  status ENUM('SCHEDULED', 'SENT', 'FAILED') NOT NULL DEFAULT 'SCHEDULED',
  scheduled_at DATETIME NOT NULL,
  sent_at DATETIME NULL,
  preview_url VARCHAR(500) NULL,
  error_message VARCHAR(500) NULL,
  job_id VARCHAR(255) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (campaign_id) REFERENCES campaigns(id)
);